### ISSUE TITLE
Derivation path

### ISSUE THREAD

**Issue by zenit70** [commercionetwork/sacco.dart#3]
Currently 'Derivation path' is a constant defined in the class 'Wallet', but it must be possible to set it.

**Comment by zenit70** [comment]
Updated the 'Wallet.derivave' method which now accepts an optional third parameter to change the last segment of the 'derivation path'.

**Comment by zenit70** [comment]
Updated tests

**Comment by marcotradenet** [comment]
In **lib/wallet.dart**      


This instruction 
```dart
print("$BASE_DERIVATION_PATH/$lastDerivationPathSegment");
```
should be deleted

`lastDerivationPathSegment` should be a integer.
Control it with something like that
```dart
if (int.parse(lastDerivationPathSegment) == null) {
 throw Exception("Invalid index format " + lastDerivationPathSegment);
}
```
or in `Wallet.derive` the parameter `lastDerivationPathSegment` should be an integer
